laravel/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
 
 
 

Route::resource('countries', 'CountryController');


Route::resource('roles', 'RoleController');

laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('fricfrac');
});


Route::resource('countries', 'CountryController');


Route::resource('roles', 'RoleController');

laravel/app/Country.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    protected $fillable = [
        'name',
        'code'
        ];
}

laravel/app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $fillable = [
        'name',
        ];
}

laravel/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

laravel/app/Http/Controllers/CarController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CarController extends Controller
{
    //
}

laravel/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

laravel/app/Http/Controllers/CountryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Country;

class CountryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $countryList = Country::all();
        return View('countries.index',array('countryList' => $countryList));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $countryList = Country::all();
        return View('countries.create',array('countryList' => $countryList));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $country = new Country;
        $country->Name =  $request->get('Name');
        $country->Code =  $request->get('Code');
      $country->save();
      
      return redirect('/countries/create');
      
      
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    $country = Country::find($id);
     $countryList = Country::all();
      return view('countries.show', array('country' => $country,'countryList' => $countryList));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $country = Country::find($id);
         $countryList = Country::all();

        return View('countries.edit',array('country' => $country,'countryList' => $countryList));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $country = Country::where('Id', $id)
        ->update(['Name' => $request->get('Name'),'Code' => $request->get('Code')]);
        
        
        
        return redirect('/countries');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
     
      
    $result=Country::where('Id',$id)->delete();
      
   
      $countryList = Country::all();

        return View('countries.index',array('countryList' => $countryList));
    }
}

laravel/app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Role;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $roleList = Role::all();
        return View('roles.index',array('roleList' => $roleList));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roleList = Role::all();
        return View('roles.create',array('roleList' => $roleList));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $role = new Role;
        $role->Name =  $request->get('Name');
      $role->save();
      
      return redirect('/roles/create');
      
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    $role = Role::find($id);
     $roleList = Role::all();
      return view('roles.show', array('role' => $role,'roleList' => $roleList));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::find($id);
         $roleList = Role::all();

        return View('roles.edit',array('role' => $role,'roleList' => $roleList));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $role = Role::where('Id', $id)
        ->update(['Name' => $request->get('Name')]);
        
        
        
        return redirect('/roles');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

    $result=Role::where('Id',$id)->delete();
      
   
      $roleList = Role::all();

        return View('roles.index',array('roleList' => $roleList));
    }
}

laravel/resources/views/countries/create.blade.php
    <main>
    <article>
         <nav class="NavReadingOne">
            <h1>Land</h1>
            <div>
            <a href={{route('countries.index')}}>Annuleren</a>
            <button type="submit" name="uc" value="insert" form="form">Insert</button>
            </div>
        </nav>
        <form id="form" method="post" action="{{ route('countries.store') }}">
             @csrf
            <div>
                <label for="Name">Naam</label>
                <input type="text" required id="Name" name="Name"/>
            </div>
             <div>
                <label for="Code">Code</label>
                <input type="text" required id="code" name="Code"/>
            </div>
       </form>
        <div id="feedback"></div>

    </article>
   @include('countries.readingAll') 
</main>

laravel/resources/views/countries/edit.blade.php
    <main>
    <article>
         <nav class="NavReadingOne">
            <h1>Land</h1>
            <div>
                <a href="index.php">Annuleren</a>
                <button type="submit" name="uc" value="update" form="form">Update</button>
            </div>
            </nav>
            
            
      <form  id="form" method="post" action="{{route('countries.update', $country->Id)}}">
          @method('PATCH')
          @csrf
         <div>
            <label for="Id">Ids</label>
            <input type="text" name="Id" id="Id" value={{ $country->Id }} readonly>
        </div>
        <div>
            <label for="Name">Naam</label>
            <input type="text" name="Name" id="Name" value={{ $country->Name }} >
        </div>
          <div>
            <label for="Code">Code</label>
            <input type="text" name="Code" id="Code" value={{ $country->Code }} >
        </div>
        
               
    </form>
        <div id="feedback"></div>

    </article>
     @include('countries.readingAll') 
</main>

laravel/resources/views/countries/index.blade.php
<main>
    <article>
        <header>
              <nav class="NavReadingOne">
            <h1>Land</h1>
            <div>
                <a href={{route('countries.create')}}>Inserting</a>
            </div>
        </nav>       
        </header>

        <fieldset>
        </fieldset>
        <div></div>

    </article>
    @include('countries.readingAll')
</main>

laravel/resources/views/countries/readingAll.blade.php
<aside>
    <table class="table">
        <tr>
           <th>Select</th>
           <th>Naam</th>
           <th>Code</th>
        </tr>
        
            @foreach($countryList as $country) 
            <tr>
                <td><a href={{route('countries.show', ['id' => ($country->Id)] )}}>-></a></td>
                <td>{{ $country->Name }}</td>
                <td>{{ $country->Code }}</td>
            </tr>
        @endforeach
    </table>
</aside>

laravel/resources/views/countries/show.blade.php
<main>
    <article>

          <nav class="NavReadingOne">
            <h1>Land</h1>
            <div>
            <a href="{{route('countries.index')}}">Annuleren</a>
            <a href="{{route('countries.edit', ['id' => ($country->Id)] )}}">Update</a>
            <a href="{{route('countries.delete', ['id' => ($country->Id)] )}}">Delete</a>
            <a href="{{route('countries.create')}}">Insert</a>
            </div>
            </nav>
    
      <form>
         <div>
            <label for="Id">Id</label>
            <input type="text" name="Id" id="Id" value="{{ $country->Id }}" readonly>
        </div>
        <div>
            <label for="Name">Naam</label>
            <input type="text" name="Name" id="Name" value="{{ $country->Name }}" readonly>
        </div>
          <div>
            <label for="Code">Code</label>
            <input type="text" name="Code" id="Code" value="{{ $country->Code }}" readonly>
        </div>
        
               
    </form>
        <div id="feedback"></div>

    </article>
    @include('countries.readingAll') 
</main>

laravel/resources/views/fricfrac.blade.php
<!DOCTYPE html>
<html lang="nl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Beheer Fric-Frac</title>
</head>
<body>
    <header>
        <h1>Fric-Frac</h1>
    </header>
    <main>
        <section>
            <a href="Person/Index.php" class="tile" id=""><span>Persoon</span></a>
            <a href="{{route('countries')}}" class="tile" id=""><span>Land</span></a>
            <a class="tile" id=""></a>
            <a class="tile" id=""></a>
            <a href="{{routes('roles')}}" class="tile" id=""><span>Role</span></a>
            <a href="User/Index.php" class="tile" id=""><span>Gebruiker</span></a>
            <a class="tile" id=""></a>
            <a href="Event/Index.php" class="tile" id=""><span>Event</span></a>
            <a href="EventCategory/Index.php" class="tile" id=""><span>Event Categorie</span></a>
            <a href="EventTopic/Index.php" class="tile" id=""><span>Event Topic</span></a>
            <a class="tile" id=""></a>
        </section>
    </main>
</body>
</html>

laravel/resources/views/roles/create.blade.php
    <main>
    <article>
         <nav class="NavReadingOne">
            <h1>Rol</h1>
            <div>
            <a href={{route('roles.index')}}>Annuleren</a>
            <button type="submit" name="uc" value="insert" form="form">Insert</button>
            </div>
        </nav>
        <form id="form" method="post" action="{{ route('roles.store') }}">
             @csrf
            <div>
                <label for="Name">Naam</label>
                <input type="text" required id="Name" name="Name"/>
            </div>
       </form>
        <div id="feedback"></div>

    </article>
   @include('roles.readingAll') 
</main>

laravel/resources/views/roles/edit.blade.php
    <main>
    <article>
         <nav class="NavReadingOne">
            <h1>Rol</h1>
            <div>
                <a href="index.php">Annuleren</a>
                <button type="submit" name="uc" value="update" form="form">Update</button>
            </div>
            </nav>
            
            
      <form  id="form" method="post" action="{{route('roles.update', $role->Id)}}">
          @method('PATCH')
          @csrf
         <div>
            <label for="Id">Ids</label>
            <input type="text" name="Id" id="Id" value={{ $role->Id }} readonly>
        </div>
        <div>
            <label for="Name">Naam</label>
            <input type="text" name="Name" id="Name" value={{ $role->Name }} >
        </div>

               
    </form>
        <div id="feedback"></div>

    </article>
     @include('roles.readingAll') 
</main>
    

laravel/resources/views/roles/index.blade.php
<main>
    <article>
        <header>
              <nav class="NavReadingOne">
            <h1>Rol</h1>
            <div>
                <a href={{route('roles.create')}}>Inserting</a>
            </div>
        </nav>       
        </header>

        <fieldset>
        </fieldset>
        <div></div>

    </article>
    @include('roles.readingAll')
</main>

laravel/resources/views/roles/readingAll.blade.php
<aside>
    <table class="table">
        <tr>
           <th>Select</th>
           <th>Naam</th>
        </tr>
        
            @foreach($roleList as $role) 
            <tr>
                <td><a href={{route('roles.show', ['id' => ($role->Id)] )}}>-></a></td>
                <td>{{ $role->Name }}</td>
                <td>{{ $role->Code }}</td>
            </tr>
        @endforeach
    </table>
</aside>

laravel/resources/views/roles/show.blade.php
<main>
    <article>

          <nav class="NavReadingOne">
            <h1>Rol</h1>
            <div>
            <a href="{{route('roles.index')}}">Annuleren</a>
            <a href="{{route('roles.edit', ['id' => ($role->Id)] )}}">Update</a>
            <a href="{{route('roles.delete', ['id' => ($role->Id)] )}}">Delete</a>
            <a href="{{route('roles.create')}}">Insert</a>
            </div>
            </nav>
    
      <form>
         <div>
            <label for="Id">Id</label>
            <input type="text" name="Id" id="Id" value="{{ $role->Id }}" readonly>
        </div>
        <div>
            <label for="Name">Naam</label>
            <input type="text" name="Name" id="Name" value="{{ $role->Name }}" readonly>
        </div>
        
    </form>
        <div id="feedback"></div>

    </article>
    @include('roles.readingAll') 
</main>